---
repos:
  - repo: 'https://github.com/willthames/ansible-lint.git'
    rev: v6.12.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        additional_dependencies:
          - ansible
        args: [--offline, --skip-list=galaxy]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.2
    hooks:
      - id: yamllint
        name: Yaml validate with yamllint
        args: [-c=.yamllint-config.yaml]